alter table public.founding_members
  add column if not exists bio text,
  add column if not exists location text,
  add column if not exists genres text,
  add column if not exists instagram_url text,
  add column if not exists youtube_url text,
  add column if not exists facebook_url text,
  add column if not exists website_url text;

create table if not exists public.stagefront_staff (
  id bigint generated by default as identity primary key,
  email text not null unique,
  role text not null check (role in ('owner', 'manager', 'moderator')),
  active boolean not null default true,
  display_name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.stagefront_staff enable row level security;

comment on table public.stagefront_staff is
  'StageFront staff roles. Environment-configured owner emails remain owners even without a row.';
