create table if not exists public.stagefront_winners (
  id bigint generated by default as identity primary key,
  display_name text not null check (char_length(display_name) between 2 and 80),
  competition text not null check (competition in ('box_battle', 'golden_voices')),
  title text not null check (char_length(title) between 2 and 100),
  season_label text not null default '',
  bio text not null default '' check (char_length(bio) <= 600),
  photo_url text,
  video_url text,
  social_url text,
  featured boolean not null default false,
  published boolean not null default true,
  won_at date,
  display_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists stagefront_winners_public_order
  on public.stagefront_winners (published, featured desc, display_order, won_at desc);

alter table public.stagefront_winners enable row level security;

drop policy if exists "Public can view published winners" on public.stagefront_winners;
create policy "Public can view published winners"
  on public.stagefront_winners for select
  using (published = true);

