create table if not exists public.original_artist_submissions (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  email text not null,
  artist_name text not null check (char_length(artist_name) between 2 and 80),
  song_title text not null check (char_length(song_title) between 1 and 120),
  genre text not null default '',
  artist_bio text not null default '' check (char_length(artist_bio) <= 600),
  story text not null check (char_length(story) between 20 and 2000),
  audio_path text not null unique,
  audio_url text not null,
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  featured boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists original_artist_public_order
  on public.original_artist_submissions (status, featured desc, created_at desc);

alter table public.original_artist_submissions enable row level security;
drop policy if exists "Public can hear approved originals" on public.original_artist_submissions;
create policy "Public can hear approved originals"
  on public.original_artist_submissions for select
  using (status = 'approved');

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'stagefront-original-music',
  'stagefront-original-music',
  true,
  52428800,
  array['audio/mpeg', 'audio/mp4', 'audio/wav', 'audio/x-wav', 'audio/aac']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

