create table if not exists public.stagefront_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique,
  username text not null unique check (username ~ '^[a-z0-9_]{3,24}$'),
  display_name text not null check (char_length(display_name) between 2 and 80),
  bio text,
  profile_image_path text,
  role text not null default 'singer' check (role in ('singer','songwriter','musician','producer','fan','host')),
  genres text,
  location text,
  looking_for text,
  is_public boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.stagefront_connections (
  id bigint generated by default as identity primary key,
  requester_id uuid not null references public.stagefront_profiles(user_id) on delete cascade,
  recipient_id uuid not null references public.stagefront_profiles(user_id) on delete cascade,
  status text not null default 'pending' check (status in ('pending','accepted','declined')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (requester_id, recipient_id),
  check (requester_id <> recipient_id)
);

create index if not exists idx_stagefront_profiles_public on public.stagefront_profiles(is_public, created_at desc);
create index if not exists idx_stagefront_connections_recipient on public.stagefront_connections(recipient_id, status, created_at desc);
create index if not exists idx_stagefront_connections_requester on public.stagefront_connections(requester_id, status, created_at desc);

alter table public.stagefront_profiles enable row level security;
alter table public.stagefront_connections enable row level security;
revoke all on public.stagefront_profiles from anon, authenticated;
revoke all on public.stagefront_connections from anon, authenticated;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('stagefront-profile-images','stagefront-profile-images',true,5242880,array['image/jpeg','image/png','image/webp'])
on conflict (id) do update set public=true, file_size_limit=excluded.file_size_limit, allowed_mime_types=excluded.allowed_mime_types;

