create table if not exists public.stagefront_posts (
  id bigint generated by default as identity primary key,
  author_id uuid not null references public.stagefront_profiles(user_id) on delete cascade,
  profile_user_id uuid references public.stagefront_profiles(user_id) on delete cascade,
  body text not null check (char_length(body) between 1 and 600),
  status text not null default 'visible' check (status in ('visible','hidden')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.stagefront_comments (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.stagefront_posts(id) on delete cascade,
  author_id uuid not null references public.stagefront_profiles(user_id) on delete cascade,
  body text not null check (char_length(body) between 1 and 300),
  status text not null default 'visible' check (status in ('visible','hidden')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_stagefront_posts_feed on public.stagefront_posts(status, created_at desc);
create index if not exists idx_stagefront_posts_profile on public.stagefront_posts(profile_user_id, status, created_at desc);
create index if not exists idx_stagefront_comments_post on public.stagefront_comments(post_id, status, created_at asc);

alter table public.stagefront_posts enable row level security;
alter table public.stagefront_comments enable row level security;
revoke all on public.stagefront_posts from anon, authenticated;
revoke all on public.stagefront_comments from anon, authenticated;
