create table if not exists public.stagefront_content_comments (
  id bigint generated by default as identity primary key,
  content_type text not null check (content_type in ('winner','original')),
  content_id bigint not null,
  author_id uuid not null references public.stagefront_profiles(user_id) on delete cascade,
  body text not null check (char_length(body) between 1 and 300),
  status text not null default 'visible' check (status in ('visible','hidden')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_stagefront_content_comments_target
  on public.stagefront_content_comments(content_type, content_id, status, created_at asc);

alter table public.stagefront_content_comments enable row level security;
revoke all on public.stagefront_content_comments from anon, authenticated;
