create table if not exists public.superfan_subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  supporter_email text not null,
  creator text not null check (creator in ('don','unk')),
  provider text not null default 'paypal' check (provider = 'paypal'),
  paypal_subscription_id text not null unique,
  paypal_plan_id text not null,
  paypal_event_id text,
  status text not null default 'approval_pending' check (status in ('approval_pending','approval','approved','active','suspended','cancelled','expired')),
  activated_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_superfan_subscriptions_user_status on public.superfan_subscriptions(user_id, status);
create index if not exists idx_superfan_subscriptions_creator_status on public.superfan_subscriptions(creator, status);

alter table public.superfan_subscriptions enable row level security;
revoke all on public.superfan_subscriptions from anon, authenticated;
